[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.pdm.scripts]
test = "python -m unittest discover -s ./tests -p *_test.py"

[build-system]
requires = ["pybuilder>=0.12.0"]
build-backend = "pybuilder.pep517"

